# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geneticsimplifier.ui'
#
# Created: Wed Sep 17 11:42:24 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GeneticSimplifier(object):
    def setupUi(self, GeneticSimplifier):
        GeneticSimplifier.setObjectName(_fromUtf8("GeneticSimplifier"))
        GeneticSimplifier.resize(587, 295)
        self.gridLayout_3 = QtGui.QGridLayout(GeneticSimplifier)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.inputLabel = QtGui.QLabel(GeneticSimplifier)
        self.inputLabel.setObjectName(_fromUtf8("inputLabel"))
        self.horizontalLayout.addWidget(self.inputLabel)
        self.inputLayerCombo = QtGui.QComboBox(GeneticSimplifier)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLayerCombo.sizePolicy().hasHeightForWidth())
        self.inputLayerCombo.setSizePolicy(sizePolicy)
        self.inputLayerCombo.setObjectName(_fromUtf8("inputLayerCombo"))
        self.horizontalLayout.addWidget(self.inputLayerCombo)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.featCountLabel = QtGui.QLabel(GeneticSimplifier)
        self.featCountLabel.setObjectName(_fromUtf8("featCountLabel"))
        self.horizontalLayout_5.addWidget(self.featCountLabel)
        self.featureCountEdit = QtGui.QLineEdit(GeneticSimplifier)
        self.featureCountEdit.setObjectName(_fromUtf8("featureCountEdit"))
        self.horizontalLayout_5.addWidget(self.featureCountEdit)
        self.featureLabel = QtGui.QLabel(GeneticSimplifier)
        self.featureLabel.setObjectName(_fromUtf8("featureLabel"))
        self.horizontalLayout_5.addWidget(self.featureLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.outputEdit_2 = QtGui.QLabel(GeneticSimplifier)
        self.outputEdit_2.setObjectName(_fromUtf8("outputEdit_2"))
        self.horizontalLayout_2.addWidget(self.outputEdit_2)
        self.outputEdit = QtGui.QLineEdit(GeneticSimplifier)
        self.outputEdit.setObjectName(_fromUtf8("outputEdit"))
        self.horizontalLayout_2.addWidget(self.outputEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.popSizeLabel = QtGui.QLabel(GeneticSimplifier)
        self.popSizeLabel.setObjectName(_fromUtf8("popSizeLabel"))
        self.horizontalLayout_3.addWidget(self.popSizeLabel)
        self.popSpin = QtGui.QSpinBox(GeneticSimplifier)
        self.popSpin.setMinimum(1)
        self.popSpin.setMaximum(10000)
        self.popSpin.setProperty(_fromUtf8("value"), 5)
        self.popSpin.setObjectName(_fromUtf8("popSpin"))
        self.horizontalLayout_3.addWidget(self.popSpin)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.restrictionLabel = QtGui.QLabel(GeneticSimplifier)
        self.restrictionLabel.setObjectName(_fromUtf8("restrictionLabel"))
        self.horizontalLayout_4.addWidget(self.restrictionLabel)
        self.spinBox = QtGui.QSpinBox(GeneticSimplifier)
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.useLocalSearchBox = QtGui.QCheckBox(GeneticSimplifier)
        self.useLocalSearchBox.setChecked(True)
        self.useLocalSearchBox.setObjectName(_fromUtf8("useLocalSearchBox"))
        self.gridLayout_3.addWidget(self.useLocalSearchBox, 4, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.evolutionGroup = QtGui.QGroupBox(GeneticSimplifier)
        self.evolutionGroup.setCheckable(True)
        self.evolutionGroup.setObjectName(_fromUtf8("evolutionGroup"))
        self.gridLayout = QtGui.QGridLayout(self.evolutionGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.generationsLabel = QtGui.QLabel(self.evolutionGroup)
        self.generationsLabel.setObjectName(_fromUtf8("generationsLabel"))
        self.horizontalLayout_6.addWidget(self.generationsLabel)
        self.genSpin = QtGui.QSpinBox(self.evolutionGroup)
        self.genSpin.setMinimum(1)
        self.genSpin.setMaximum(100)
        self.genSpin.setObjectName(_fromUtf8("genSpin"))
        self.horizontalLayout_6.addWidget(self.genSpin)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mateLabel = QtGui.QLabel(self.evolutionGroup)
        self.mateLabel.setObjectName(_fromUtf8("mateLabel"))
        self.horizontalLayout_7.addWidget(self.mateLabel)
        self.mateCombo = QtGui.QComboBox(self.evolutionGroup)
        self.mateCombo.setObjectName(_fromUtf8("mateCombo"))
        self.horizontalLayout_7.addWidget(self.mateCombo)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.croosLabel = QtGui.QLabel(self.evolutionGroup)
        self.croosLabel.setObjectName(_fromUtf8("croosLabel"))
        self.horizontalLayout_8.addWidget(self.croosLabel)
        self.crossSpin = QtGui.QSpinBox(self.evolutionGroup)
        self.crossSpin.setMinimum(1)
        self.crossSpin.setMaximum(100)
        self.crossSpin.setProperty(_fromUtf8("value"), 50)
        self.crossSpin.setObjectName(_fromUtf8("crossSpin"))
        self.horizontalLayout_8.addWidget(self.crossSpin)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.mutationLabel = QtGui.QLabel(self.evolutionGroup)
        self.mutationLabel.setObjectName(_fromUtf8("mutationLabel"))
        self.horizontalLayout_9.addWidget(self.mutationLabel)
        self.mutationSpin = QtGui.QSpinBox(self.evolutionGroup)
        self.mutationSpin.setMinimum(1)
        self.mutationSpin.setMaximum(100)
        self.mutationSpin.setProperty(_fromUtf8("value"), 20)
        self.mutationSpin.setObjectName(_fromUtf8("mutationSpin"))
        self.horizontalLayout_9.addWidget(self.mutationSpin)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.geneLabel = QtGui.QLabel(self.evolutionGroup)
        self.geneLabel.setObjectName(_fromUtf8("geneLabel"))
        self.horizontalLayout_10.addWidget(self.geneLabel)
        self.geneSpin = QtGui.QSpinBox(self.evolutionGroup)
        self.geneSpin.setMinimum(1)
        self.geneSpin.setMaximum(100)
        self.geneSpin.setProperty(_fromUtf8("value"), 5)
        self.geneSpin.setObjectName(_fromUtf8("geneSpin"))
        self.horizontalLayout_10.addWidget(self.geneSpin)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.evolutionGroup, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 5, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(GeneticSimplifier)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 6, 1, 1, 1)

        self.retranslateUi(GeneticSimplifier)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GeneticSimplifier.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GeneticSimplifier.reject)
        QtCore.QMetaObject.connectSlotsByName(GeneticSimplifier)

    def retranslateUi(self, GeneticSimplifier):
        GeneticSimplifier.setWindowTitle(QtGui.QApplication.translate("GeneticSimplifier", "GeneticSimplifier", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Input Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLayerCombo.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Just line layers can be used.", None, QtGui.QApplication.UnicodeUTF8))
        self.featCountLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "The selected layer contains:", None, QtGui.QApplication.UnicodeUTF8))
        self.featureLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "features", None, QtGui.QApplication.UnicodeUTF8))
        self.outputEdit_2.setText(QtGui.QApplication.translate("GeneticSimplifier", "Output Layer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.popSizeLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Population Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.popSpin.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Number of possible solutions tested for each line.", None, QtGui.QApplication.UnicodeUTF8))
        self.restrictionLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Shape Restriction:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Maximum deviation from the original line.", None, QtGui.QApplication.UnicodeUTF8))
        self.useLocalSearchBox.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Makes the number of vertexes in the simplification quite smaller but makes the algorithm quite slower as well.", None, QtGui.QApplication.UnicodeUTF8))
        self.useLocalSearchBox.setText(QtGui.QApplication.translate("GeneticSimplifier", "Use local search?", None, QtGui.QApplication.UnicodeUTF8))
        self.evolutionGroup.setTitle(QtGui.QApplication.translate("GeneticSimplifier", "Use Evolution?", None, QtGui.QApplication.UnicodeUTF8))
        self.generationsLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Number of Generations:", None, QtGui.QApplication.UnicodeUTF8))
        self.genSpin.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Number of generations analyzed.", None, QtGui.QApplication.UnicodeUTF8))
        self.mateLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Mate Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.mateCombo.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Type of crossover applied.", None, QtGui.QApplication.UnicodeUTF8))
        self.croosLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Crossover Probability (%):", None, QtGui.QApplication.UnicodeUTF8))
        self.crossSpin.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Probability to apply crossover.", None, QtGui.QApplication.UnicodeUTF8))
        self.mutationLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Mutation Probability (%):", None, QtGui.QApplication.UnicodeUTF8))
        self.mutationSpin.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Mutation probability on a possible solution.", None, QtGui.QApplication.UnicodeUTF8))
        self.geneLabel.setText(QtGui.QApplication.translate("GeneticSimplifier", "Gene Mutation Probability (%):", None, QtGui.QApplication.UnicodeUTF8))
        self.geneSpin.setToolTip(QtGui.QApplication.translate("GeneticSimplifier", "Probability to change the participation of a vertex in a possible solution.", None, QtGui.QApplication.UnicodeUTF8))

